config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  resources :users, except: :new
  resources :meetings, except: [:index, :show]
  resources :tas, only: [:index, :show]
  resources :students, only: [:show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/models/ta.rb
class Ta < User
	has_many :meetings, dependent: :destroy
	has_many :students, through: :meetings
	belongs_to :course
end

app/controllers/tas_controller.rb
class TasController < ApplicationController

  def index
    # Only allow student to see this view
    if !current_user
      redirect_to root_path
  	elsif current_user.type == "Student"
  		@tas = Ta.where(course_id: current_user.course_id)
    elsif current_user.type == "Ta"
      redirect_to ta_path(current_user)
  	end
  end

  def show
    @ta = Ta.friendly.find(params[:id])
    @groups = Ta.find(@ta).meetings.group_by { |t| Date.commercial(Time.now.year, t.start_time.to_date.cweek) }
    unless current_user.id == @ta.id or current_user.type == "Student"
      if current_user.type == "Ta"
        redirect_to ta_path(current_user)
      end
    end
  end

end

app/helpers/tas_helper.rb
module TasHelper
end

app/views/tas/index.html.erb
<div class="container">
  <div class="text-center">
    <h1><%= Course.find(current_user.course_id).name %> Instructors</h1>
  </div>
</div>
<div class="container well">
  <div class="col-lg-12 text-center">
    <% if @tas %>
      <% @tas.each do |ta| %>
        <div class="col-sm-6 col-md-4 col-lg-4 text-center">
          <div class="thumbnail tas_thumbnail">
            <div class="caption">
              <div id="home" class="tab-pane fade in active">
                <div class="img-thumb-holder tas_thumbnail_pic">
                  <%= image_tag ta.image.url(:thumb) %>
                </div>
                <% avalibility_count = ta.meetings.select {|meeting| meeting.student_id == nil }.count %>
                <h2><%= link_to ta.name.titleize, ta_path(ta) %></h2>
                <% if avalibility_count > 1 %>
                  <%= link_to (avalibility_count.to_s + " Available Meetings"), ta_path(ta), class: "btn btn-primary" %>
                <% elsif avalibility_count == 1 %>
                  <%= link_to (avalibility_count.to_s + " Available Meeting"), ta_path(ta), class: "btn btn-primary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% else %>
        <h1 text-center>There aren't any Instructors signed up!</h1>
    <% end %>
  </div>
</div>

app/views/tas/show.html.erb
<div class="container" id="ta_profile">
  <div class="col-md-3 col-sm-12 text-center word-wrap well">
   <div class="img-thumb-holder">
      <%= image_tag @ta.image.url(:thumb) %>
    </div>
    <div>
      <h4><%= @ta.name.titleize %></h4>
      <h4><%= @ta.email %></h4>
      <h4 class="text-center"><%= fa_icon('clock-o') %> Joined on <%= @ta.created_at.to_date.to_formatted_s(:long_ordinal) %></h4>
        <% if current_user == @ta %>
          <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-primary" %>
          <%= link_to "Add a Meeting", new_meeting_path, class: "btn btn-primary" %>
        <% elsif current_user.type == "Student" %>
          <%= link_to "All Instructors", tas_path, class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
  <div class="col-md-9 col-sm-12 text-center well" id="week-holder">
    <% if @groups.empty? and current_user.type == "Student" %>
      <div class="alert alert-info">
        <h3><%= @ta.name.titleize %> hasn't had any available meeting.</h3>
        <h4>Click <a href="mailto:<%= @ta.email %>?Subject=I%20would%20like%20to%20schedule%20a%20meeting">here</a> to email <%= @ta.name.titleize %></h4>
      </div>
    <% elsif @groups.empty? and current_user.type == "Ta" %>
      <div class="alert alert-info">
        <h3>You don't have any available meetings yet.</h3>
      </div>
    <% else %>
      <% @groups.each do |week, meetings| %>
        <div class="week">
          <% if @groups.length > 1 %>
            <h2><%= week.strftime("%b/%d/%Y") %> - <%= (week + 6).strftime("%b/%d/%Y") %></h2>
            <button class="btn btn-secondary prev">Prev</button>
            <button class="btn btn-secondary next">Next</button>
          <% else %>
            <h2><%= week.to_formatted_s(:long) %> - <%= (week + 6).to_formatted_s(:long) %></h2>
          <% end %>
          <% day = meetings.uniq{|meeting| meeting.start_time.localtime.strftime("%A")}.sort_by { |meeting| meeting.start_time } %>
          <ul class="nav nav-tabs">
            <% (0...day.length).each do |i| %>
              <li><a data-toggle="tab" href="#<%= week %><%= day[i].start_time.localtime.strftime("%m-%d") %>"><%= day[i].start_time.localtime.strftime("%a %m/%d") %></a></li>
            <% end %>
          </ul>
          <div class="tab-content">
            <% (0...day.length).each do |j| %>
              <div id="<%= week %><%= day[j].start_time.localtime.strftime("%m-%d") %>" class="tab-pane fade">
                <% meetings.each do |meeting| %>
                  <% local_start = meeting.start_time.localtime %>
                  <% local_end = meeting.end_time.localtime %>
                  <% if local_start.strftime("%A") == day[j].start_time.localtime.strftime("%A") %>
                    <div class="meeting-wrapper">
                      <% if meeting.subject != nil %>
                        <h3><%= meeting.subject %></h3>
                      <% end %>
                      <h4><strong>Date:</strong> <%= local_start.to_date %></h4>
                      <h4><strong>Start:</strong> <%= local_start.strftime("%H:%M") %></h4>
                      <h4><strong>End:</strong> <%= local_end.strftime("%H:%M") %></h4>
                      <% if current_user && current_user.type == "Student" %>
                        <% if meeting.student_id == nil %>
                          <%= link_to "Reserve", edit_meeting_path(meeting), class: "btn btn-primary" %>
                        <% else %>
                          <h4>Reserved by: <%= link_to Student.find(meeting.student_id).name, student_path(meeting.student_id) %></h4>
                        <% end %>
                      <% elsif current_user && current_user.type == "Ta" %>
                        <% if meeting.student_id == nil %>
                          <h3><span class="label label-primary">Available</span></h3>
                          <%= link_to fa_icon("pencil-square-o"), edit_meeting_path(meeting), class: "edit-meeting" %>
                          <%= link_to fa_icon("trash-o"), meeting, method: :delete, data: {confirm: "Are your sure?"}, class: "delete-meeting" %>
                        <% else %>
                          <h4>Reserved by: <%= link_to Student.find(meeting.student_id).name, student_path(meeting.student_id) %></h4>
                        <% end %>
                      <% elsif !current_user %>
                        <%= link_to "Reserve", login_path, class: "btn btn-success" %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>