config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  resources :users, except: :new
  resources :meetings, except: [:index, :show]
  resources :tas, only: [:index, :show]
  resources :students, only: [:show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/views/partials/HeaderPartial.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Knock-Knock</h1>
            <hr>
            <p>Find a availabe tutors to provide personalized assistance in your learning process</p>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Book a tutor</a> <a href="#about" class="btn btn-primary btn-xl page-scroll">Become a tutor</a>
        </div>
    </div>
</header>

app/views/partials/NavBarPartial.html.erb
<nav id='nav' class='navbar navbar-default navbar-fixed-top'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-navbar'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <a class="siteLogo siteLogoNav navbar-brand page-scroll a" href="/">Knock Knock</a>
    </div>
    <div class='navbar-collapse collapse' id='bs-navbar'>
      <ul class='nav navbar-nav pull-right'>
        <% if current_user %>
          <% if params[:controller] == 'user' && params[:action] == 'show' %>
          <li>
            <%= link_to 'New Meeting', new_meeting_post_path(@meeting, @post) %>
          </li>
          <% end %>
          <li>
            <%= link_to 'Profile', user_path(current_user) %>
          </li>
          <li>
            <%= link_to 'Logout', logout_path %>
          </li>
          <% else %>
          <li>
            <%= link_to 'Sign Up', new_user_path %>
          </li>
          <li>
            <%= link_to 'Login', login_path %>
          </li>
        <% end %>
      </ul>
      <ul class='nav navbar-nav pull-left'>
      <% if params[:controller] == 'meeting' || params[:controller] == 'posts' %>
        <li>
          <%= link_to @meeting.name, meeting_path(@meeting) %>
        </li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>