config/routes.rb
Rails.application.routes.draw do

  root to: 'users#new'

  resources :users, except: :new
  resources :meetings, except: [:index, :show]
  resources :tas, only: [:index, :show]
  resources :students, only: [:show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Knock-Knock</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= favicon_link_tag asset_path('favicon.png'), type:'image/png' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav id='nav' class='navbar navbar-default'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-navbar'>
        <span class='sr-only'>Toggle navigation</span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </button>
      <%= link_to "Knock Knock", root_path, class: "siteLogo siteLogoNav navbar-brand page-scroll a" %>
    </div>
    <div class='navbar-collapse collapse' id='bs-navbar'>
      <ul class='nav navbar-nav pull-right'>
        <% if current_user %>
          <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% if current_user.type == "Ta" %>
                <li><%= link_to 'Profile', ta_path(current_user) %></li>
              <% elsif current_user.type == "Student" %>
                <li><%= link_to 'Profile', student_path(current_user) %></li>
              <% end %>
              <li><%= link_to 'Logout', logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li><a href="/#sign-up">Sign Up</a></li>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
  </nav>

  <!-- error message -->
  <% flash.each do |name, msg| %>
    <div class="alert <%= name == 'error' ? 'alert-danger' : 'alert-info' %>">
      <div class="container">
        <%= msg %>
      </div>
    </div>
  <% end %>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
</body>
</html>